name: CI
on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: build-image
        env: 
          image_name: github-ci-demo
          docker_repo: registry.cn-hangzhou.aliyuncs.com
          tag: latest
        run:  |
          echo "login aliyun docker repo" 
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }}  --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build . --file Dockerfile --tag $docker_repo/$image_name:$tag
          docker push $docker_repo/$iamge_name:$tag          
      